language: java
jdk:
  - oraclejdk8
  
after_success:
  - echo "<settings><servers><server><id>snapshot-repository</id><username>\${env.OSS_USERNAME}</username><password>\${env.OSS_PASSWORD}</password></server></servers></settings>" > ~/travis-settings.xml
  - mvn deploy --settings ~/travis-settings.xml
