language: java

after_success:
  - echo "<settings><servers><server><id>ossrh</id><username>\${env.OSS_USERNAME}</username><password>\${env.OSS_PASSWORD}</password></server></servers></settings>" > ~/travis-settings.xml
  - mvn deploy --settings ~/travis-settings.xml
